version: '3'
services:
  app:
    container_name: review
    restart: on-failure
    build: .
    ports:
      - '80:3003'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
