version: '3'
services:
  app:
    container_name: review
    restart: on-failure
    build: .
    ports:
      - '3003:3003'
    networks: 
      - fec-trip
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - fec-trip
    volumes: 
      - mongo-data:/data/db

networks: 
  fec-trip:
    driver: bridge
volumes: 
  mongo-data:
    driver: local

